version: "2"
services:
  nest:
    build: .
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - .env:/app/.env
      - ./upload:/app/upload
    # ports:
    #   - 3000:3000
    restart: unless-stopped
    scale: 2
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: mt-nest-api-nginx
    depends_on:
      - nest
    environment:
      - NGINX_SERVER_NAME=localhost
      - NEST_HOST_1=nest-awesome-api-nest-1
      - NEST_HOST_2=nest-awesome-api-nest-2
      - NEST_PORT=3000
      - NGINX_MAX_BODY=100M
    ports:
      - 81:80
      - 443:443
    volumes:
      - ./certs/localhost.pem:/etc/nginx/ssl/localhost.pem
      - ./certs/localhost-key.pem:/etc/nginx/ssl/localhost-key.pem
  db:
    image: postgres:12
    container_name: mt-nest-api-db
    environment:
      POSTGRES_DB: nest
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql
  redis:
    image: redis:5
    container_name: mt-api-redis
    ports:
      - 6379:6379
  redis-commader:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:mt-api-redis:6379
    ports: 
      - 8082:8081
    depends_on:
      - redis
volumes:
  postgresdata:
